# Generated by Django 3.2.3 on 2021-05-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviews',
            new_name='review',
        ),
    ]
