# Generated by Django 2.2.4 on 2021-05-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0003_auto_20210526_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='raiting',
        ),
    ]
